version: 2
jobs:
  build-job:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - run:
          name: Test
          command: |
            echo "It works"
  deploy-job:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - run:
          name: Test
          command: |
            echo "It works"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-job
      - deploy-job
