version: 2
jobs:
  build-job:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - run:
          name: Test
          command: |
            set -x
            sleep $CIRCLE_BUILD_NUM
  deploy-job:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - run:
          name: Test
          command: |
            echo "Done!"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
