version: 2
jobs:
  build:
    machine: true
    shell: sudo /bin/bash
    steps:
      - checkout
      - run:
          name: Check docker info
          command: |
            docker info
            docker version
      - run: ls -la /var/run/docker.sock
      - run: docker ps -a
      - run: docker images
      - run: ps auxfww
      - run: docker build -t foo .
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
